# Generated by Django 3.2.10 on 2021-12-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
