# Generated by Django 3.2.10 on 2021-12-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='page_title',
            new_name='content_title',
        ),
    ]
