# Generated by Django 3.2.10 on 2021-12-24 06:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_page_title_homepage_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
