# Generated by Django 3.0.3 on 2022-01-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_content_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_subSubtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
