# Generated by Django 3.0.3 on 2022-01-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_flexpage_content_subsubtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexpage',
            old_name='content_subSubtitle',
            new_name='content_subtitle',
        ),
        migrations.RenameField(
            model_name='flexpage',
            old_name='subtitle',
            new_name='content_title',
        ),
    ]
